#!/bin/sh
# @version $Revision$ ($Author$) $Date$
#
# echo SCRIPTS_DIR=${SCRIPTS_DIR}
#make absolute path
#pushd ${SCRIPTS_DIR}
SAVE_DIR=`pwd`
cd ${SCRIPTS_DIR}
SCRIPTS_DIR=`pwd`
#popd
cd ${SAVE_DIR}
# echo SCRIPTS_DIR=${SCRIPTS_DIR}
. ${SCRIPTS_DIR}/version.sh
BLUECOVE_TESTER_HOME=`dirname ${SCRIPTS_DIR}`
BLUECOVE_EXAMPLES_HOME=`dirname ${BLUECOVE_TESTER_HOME}`
BLUECOVE_PROJECT_HOME=`dirname ${BLUECOVE_EXAMPLES_HOME}`/bluecove
BLUECOVE_JAR="${BLUECOVE_PROJECT_HOME}/target/bluecove-${BLUECOVE_VERSION}.jar"
BLUECOVE_GPL_PROJECT_HOME=`dirname ${BLUECOVE_EXAMPLES_HOME}`/bluecove-gpl
BLUECOVE_GPL_JAR="${BLUECOVE_GPL_PROJECT_HOME}/target/bluecove-gpl-${BLUECOVE_VERSION}.jar"
BLUECOVE_TESTER_JAR="${BLUECOVE_TESTER_HOME}/target/bluecove-tester-${BLUECOVE_VERSION}.jar"
BLUECOVE_TESTER_APP_JAR="${BLUECOVE_TESTER_HOME}/target/bluecove-tester-${BLUECOVE_VERSION}-app.jar"
BLUECOVE_3RDPARTY_HOME=`dirname ${BLUECOVE_EXAMPLES_HOME}`/3p
BLUECOVE_MAIN=net.sf.bluecove.se.Main
#echo BLUECOVE_TESTER_APP_JAR=${BLUECOVE_TESTER_APP_JAR}
